### ISSUE TITLE
Unclear which command to run with FWTS to get target output

### ISSUE THREAD

**Issue by zachlatta** [farjump/fwtr#1]
It's not clear in the README which command we should run with FWTS to get the expected output directory.

It'd be even better if there was a script included to generate the proper directory structure with the expected output, ready to commit.

**Comment by Julio-Guerra** [comment]
This repo isn't really meant to be a guide since options depend on the version of the tools. So we simply provided pointers to their websites, nothing more. 

The README (tries) to explain that any output is valid. It is up to you to store them according to the way you started. But to answer you, the launched command is in the logs and it is automatically launched by fwts live image, it ends up storing them in the USB key so that you can copy them afterwards.

I think writing a tool to point where to store it is difficult for that reason and the first folder (vendor/board/tool) are easy enough to make such a tool useless.

Anyway, we could help you during a merge request.
