### ISSUE TITLE
Laptop file structure

### ISSUE THREAD

**Issue by kageurufu** [farjump/fwtr#8]
Since this is so early, theres little to no layout for laptops. I have the data for the Lenovo Y510P, and would like to submit, but do not know the proper way to structure this

So far I have

fwtr/lenovo/ideapad/y510p/74CN31WW/[results]

I wanted to verify this before pull requesting

I would also prefer to remove the asset tag and serial numbers, if that is acceptable

**Comment by Julio-Guerra** [comment]
We already have a laptop result in `/samsung/np940x3g/ami/P05ACJ.128.140819.dg/fwts/1`.
We discussed how to store it in issue #3 according to the `results.log` file which includes who are the system (in your case laptop), bios and board vendors.

What matters most is how a end customer (you, me) can get the board:
- if the motherboard is in the system's catalogue, then the motherboard vendor name should be used.
- if the motherboard is specifically designed for another system, then the system vendor name should be used.

For example, in Samsung's NP940X3G laptop, AMI is the motherboard supplier but you won't be able to buy it yourself for your own usage.

Anyway, why can we accept errors? Because we have great search engines and I imagine people will look into fwtr copy/pasting their bios version, board name or anything that could identify their motherboard. And every information is stored in the results, so there would be a match.

Hope this helps. And again, do not hesitate to create your pull request. I'll review it and rework it if required :)
